Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m.softmax(0)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mm[49m[38;5;241;43m.[39;49m[43msoftmax[49m[43m([49m[38;5;241;43m0[39;49m[43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/maskedtensor/core.py:218[0m, in [0;36mMaskedTensor.__torch_function__[0;34m(cls, func, types, args, kwargs)[0m
[1;32m    216[0m logging[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mtf redispatching to td[39m[38;5;124m"[39m)
[1;32m    217[0m [38;5;28;01mwith[39;00m torch[38;5;241m.[39m_C[38;5;241m.[39mDisableTorchFunction():
[0;32m--> 218[0m     ret [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    219[0m     [38;5;28;01mif[39;00m func [38;5;129;01min[39;00m get_default_nowrap_functions():
[1;32m    220[0m         [38;5;28;01mreturn[39;00m ret

File [0;32m~/.local/lib/python3.8/site-packages/maskedtensor/core.py:230[0m, in [0;36mMaskedTensor.__torch_dispatch__[0;34m(cls, func, types, args, kwargs)[0m
[1;32m    228[0m [38;5;129m@classmethod[39m
[1;32m    229[0m [38;5;28;01mdef[39;00m [38;5;21m__torch_dispatch__[39m([38;5;28mcls[39m, func, types, args, kwargs):
[0;32m--> 230[0m     func [38;5;241m=[39m [43mfunc[49m[38;5;241;43m.[39;49m[43moverloadpacket[49m
[1;32m    232[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mmaskedtensor[39;00m [38;5;28;01mimport[39;00m apply_reduction, is_reduction
[1;32m    234[0m     [38;5;28;01mif[39;00m is_reduction(func):

[0;31mAttributeError[0m: 'builtin_function_or_method' object has no attribute 'overloadpacket'
AttributeError: 'builtin_function_or_method' object has no attribute 'overloadpacket'

